### PR TITLE
Use ViewPropertyAnimator

### PR DESCRIPTION
**Pull request by PatrickDattilio**
The ObjectAnimators can be replaced with a single chained ViewPropertyAnimator call off of the imagebutton itself.

### CODE REVIEW

**Comment by captswag** [comment]
Thanks for this great piece of information. I checked it out locally, and it works fine. Could you please update the code on line number 144 - 153 where I am still using ObjectAnimator for the reverse animation, and remove the unused import statements [android.animation.ObjectAnimator]. Then I will merge the pull request. Thanks.

**Comment by PatrickDattilio** [comment]
Replaced the other set

**Comment by captswag** [comment]
Merged, thanks. Nice tip.

**Comment by captswag** [comment]
Merged, thank you.

**Pull request merged**
